### ISSUE TITLE
Support for Vivoactive 5

### ISSUE THREAD

**Issue by nsekulov** [j-kaltes/Kerfstok#1]
Could you please add support for Vivoactive active 5

**Comment by j-kaltes** [comment]
Version 1.5.4 now includes support for Vivoactive 5:
https://apps.garmin.com/en-US/apps/b6348ccc-86d8-4780-8013-d9e19fed5260#compatible-devices
Please tell me if it works or not.

**Comment by nsekulov** [comment]
It Works thank you very much!
